.github/workflows/tox.yml
conftest.py
molecule_docker/playbooks/Dockerfile.j2
molecule_docker/playbooks/create.yml
molecule_docker/playbooks/validate-dockerfile.yml
molecule_docker/test/test_func.py
setup.cfg
tox.ini

Fixes regression that happened when we moved driver outside molecule core. Scenarios not using pre-build image option and missing a custom Dockerfile were affected by this bug.

Added missing embedded Dockerfile

---

tox.ini

Apparently the 2020-resolver is not reliable and causes endless loops during install.
Related: https://github.com/pypa/pip/issues/8713

Disable broken pip 2020-resolver

---

molecule_docker/test/test_func.py
setup.cfg

Marked as major because it will require a major version bump due to bumped dependency.
Related: https://github.com/ansible-community/molecule/pull/2917

Make tests compatible with molecule 3.2

---

molecule_docker/driver.py

It is called 'env' not 'environment', like the option of docker_container
Ansible module.

Fix references to 'env' option

---

molecule_docker/playbooks/create.yml
molecule_docker/playbooks/destroy.yml
molecule_docker/playbooks/filter_plugins/get_docker_networks.py

Fixes ansible-community/molecule-docker#47

Fix unnecessary warnings when creating/destroying docker networks

---

molecule_docker/playbooks/create.yml

Pass mounts parameter to docker_container in create.yml. Mounts are supported by the Ansible docker_container plugin but were not passed along if specified for a platform in molecule.yml.

Pass mounts to docker_container in create.yml

---

molecule_docker/playbooks/destroy.yml

I noticed `molecule destroy` show quite some information:
```
TASK [Wait for instance(s) deletion to complete] *******************************
FAILED - RETRYING: Wait for instance(s) deletion to complete (300 retries left).
changed: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '333564963040.96040', 'results_file': '/home/robertdb/.ansible_async/333564963040.96040', 'changed': True, 'failed': False, 'item': {'command': '/sbin/init', 'image': 'robertdebock/fedora:rawhide', 'name': 'xinetd-fedora-rawhide', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
```
This change reduces that ouput to:
```
TASK [Wait for instance(s) deletion to complete] *******************************
FAILED - RETRYING: …
```

Cleanup output, use `loop` over `with_items`.

---

molecule_docker/playbooks/create.yml

This is useful when using `command: /sbin/init`.
```
platforms:
- name: instance
command: /sbin/init
stop_signal: RTMIN+3
```
Seee also https://bugzilla.redhat.com/show_bug.cgi?id=1201657

Pass stop_signal and kill_signal to docker_container in create.yml

---

molecule_docker/driver.py
molecule_docker/playbooks/cleanup.yml
molecule_docker/playbooks/create.yml

PR intend to fix #50 by changing the build path to either:
* a path specified in the molecule.yml file
* the scenario directory where molecule looks for custom Dockerfile.j2 (so path specified in COPY instruction remain valid)
There may be implications I didn't think of but from the basic tests I've made "it just work on my laptop" :)

change docker image build path

---

molecule_docker/playbooks/create.yml

Fix bug introduced by #51 where ansible would choke when path is not specified and pre_build_image is false.

Fix condition when path is missing

---

molecule_docker/driver.py
molecule_docker/playbooks/create.yml
molecule_docker/playbooks/destroy.yml
molecule_docker/playbooks/validate-dockerfile.yml

Running in an ansible-core project, I get this failure while running a molecule test with the docker driver:
```
INFO     Running default > destroy
ERROR! couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/var/home/yajo/mydevel/mando/.venv/lib/python3.9/site-packages/molecule_docker/playbooks/destroy.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
tasks:
- name: Destroy molecule instance(s)
^ here
```
After fixing the playbooks, it still fails with:
```
PLAY [prepare] *****************************************************************
TASK [Gathering Facts] …
```

fix: specify docker modules namespace

---

.ansible.cfg
.github/workflows/tox.yml
README.rst
ansible.cfg
molecule_docker/driver.py
molecule_docker/playbooks/create.yml
molecule_docker/playbooks/destroy.yml
molecule_docker/test/test_func.py
setup.cfg
tox.ini

* Stop using older docker modules and rely on `community.docker`. Still compatible with ansible 2.9-2.11, even with the core ansible versions but requires installation of `community.docker`, which must be done by the user.
* Document use of `community.docker`
* Refactor testing and include testing of all 3 supported versions of ansible

Rely on community.docker collection

---

.pre-commit-config.yaml
molecule_docker/playbooks/create.yml
molecule_docker/playbooks/validate-dockerfile.yml

Replace yamllint with ansible-lint, which also includes yamllint.
This is also fixing newly reported issues.

Enable ansible-lint

---

src/molecule_docker/playbooks/tasks/delete_network.yml

Fixed delete network task to check if owner label is defined and if so, delete the network if it's owned by molecule.
Fixes issue #96

fixed delete network task when option

---

src/molecule_docker/playbooks/create.yml

This enables setting the architecture when building a Molecule compatible container See #114

Add platform to the Build an Ansible compatible image task

---

.github/workflows/tox.yml
mypy.ini
setup.cfg
tox.ini

Since https://github.com/ansible-community/molecule/pull/3436 molecule
doesn't support python < 3.8, so we drop support for python 3.6 and 3.7.

Drop python 3.6 and 3.7 support

---

.github/workflows/tox.yml
tox.ini

That is a requirement for switching to molecule v3+ but we make this
change separately as we need to update our testing pipelines.
Required-By: #155

Require ansible-core 2.12 or newer

---

.github/workflows/tox.yml
requirements.yml
src/molecule_docker/driver.py
src/molecule_docker/playbooks/create.yml
src/molecule_docker/test/scenarios/with-context/molecule/default/Dockerfile.j2
src/molecule_docker/test/scenarios/with-context/molecule/default/converge.yml
src/molecule_docker/test/scenarios/with-context/molecule/default/molecule.yml
src/molecule_docker/test/test_func.py

Ensure the docker context are copied to work dir.
Related to #168

Sync docker context

---

src/molecule_docker/playbooks/create.yml
src/molecule_docker/playbooks/validate-dockerfile.yml

Fix lint issue

---

src/molecule_docker/driver.py
src/molecule_docker/playbooks/create.yml

This fixes systemd support in Debian >=11 containers.
Minimal platforms configuration in `molecule.yml`:
```
platforms:
- name: instance
image: debian:bullseye
command: /lib/systemd/systemd
privileged: true
cgroupns_mode: private
```
Example `Dockerfile.j2`:
```
FROM debian:bullseye
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3 sudo bash ca-certificates \
iproute2 python3-apt aptitude
RUN apt-get update && apt-get install -y systemd; \
systemctl mask getty@tty1.service; \
systemctl mask systemd-timesyncd.service;
RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
/etc/systemd/system/*.wants/* \
/lib/systemd/system/local-fs.target.wants/* \
/lib/systemd/system/sockets.target.wants/*udev* \
/lib/systemd/system/sockets.target.wants/*initctl* \ …
```

Add support for cgroupns_mode

---

src/molecule_docker/playbooks/create.yml
src/molecule_docker/playbooks/destroy.yml

In certain cases where the home directory environment variable (`$HOME`) is set and it doesn't match the home directory in `/etc/passwd` the `async_status` task will fail with a message such as:
```
"results_file": "/home/runner/.ansible_async/25596
1675523.4961", "started": 1}, "msg": "could not find job", "results_file": "/root/.ansible_async/255961675523.4961"
```
This fixes that issue by setting the `HOME` environment variable as the `ansible_async_dir` variable that 'async_status' task accepts as a override.
I ran into this issue with the `creator-ee` container that is supposedly going to be fixed but I'm proposing this change as this issue could still occur in other containers/environments.
Related:
https://github.com/ansible/ansible-runner/issues/1024 …

fix: make sure directory for async is correctly set
